#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("PurposeColor.Droid.Resource", IsApplication=true)]

namespace PurposeColor.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::AndroidHUD.Resource.Attribute.ahBarColor = global::PurposeColor.Droid.Resource.Attribute.ahBarColor;
			global::AndroidHUD.Resource.Attribute.ahBarLength = global::PurposeColor.Droid.Resource.Attribute.ahBarLength;
			global::AndroidHUD.Resource.Attribute.ahBarWidth = global::PurposeColor.Droid.Resource.Attribute.ahBarWidth;
			global::AndroidHUD.Resource.Attribute.ahCircleColor = global::PurposeColor.Droid.Resource.Attribute.ahCircleColor;
			global::AndroidHUD.Resource.Attribute.ahDelayMillis = global::PurposeColor.Droid.Resource.Attribute.ahDelayMillis;
			global::AndroidHUD.Resource.Attribute.ahRadius = global::PurposeColor.Droid.Resource.Attribute.ahRadius;
			global::AndroidHUD.Resource.Attribute.ahRimColor = global::PurposeColor.Droid.Resource.Attribute.ahRimColor;
			global::AndroidHUD.Resource.Attribute.ahRimWidth = global::PurposeColor.Droid.Resource.Attribute.ahRimWidth;
			global::AndroidHUD.Resource.Attribute.ahSpinSpeed = global::PurposeColor.Droid.Resource.Attribute.ahSpinSpeed;
			global::AndroidHUD.Resource.Attribute.ahText = global::PurposeColor.Droid.Resource.Attribute.ahText;
			global::AndroidHUD.Resource.Attribute.ahTextColor = global::PurposeColor.Droid.Resource.Attribute.ahTextColor;
			global::AndroidHUD.Resource.Attribute.ahTextSize = global::PurposeColor.Droid.Resource.Attribute.ahTextSize;
			global::AndroidHUD.Resource.Drawable.ic_errorstatus = global::PurposeColor.Droid.Resource.Drawable.ic_errorstatus;
			global::AndroidHUD.Resource.Drawable.ic_successstatus = global::PurposeColor.Droid.Resource.Drawable.ic_successstatus;
			global::AndroidHUD.Resource.Drawable.roundedbg = global::PurposeColor.Droid.Resource.Drawable.roundedbg;
			global::AndroidHUD.Resource.Drawable.roundedbgdark = global::PurposeColor.Droid.Resource.Drawable.roundedbgdark;
			global::AndroidHUD.Resource.Id.loadingImage = global::PurposeColor.Droid.Resource.Id.loadingImage;
			global::AndroidHUD.Resource.Id.loadingProgressBar = global::PurposeColor.Droid.Resource.Id.loadingProgressBar;
			global::AndroidHUD.Resource.Id.loadingProgressWheel = global::PurposeColor.Droid.Resource.Id.loadingProgressWheel;
			global::AndroidHUD.Resource.Id.textViewStatus = global::PurposeColor.Droid.Resource.Id.textViewStatus;
			global::AndroidHUD.Resource.Layout.loading = global::PurposeColor.Droid.Resource.Layout.loading;
			global::AndroidHUD.Resource.Layout.loadingimage = global::PurposeColor.Droid.Resource.Layout.loadingimage;
			global::AndroidHUD.Resource.Layout.loadingprogress = global::PurposeColor.Droid.Resource.Layout.loadingprogress;
			global::AndroidHUD.Resource.String.library_name = global::PurposeColor.Droid.Resource.String.library_name;
			global::AndroidHUD.Resource.Styleable.ProgressWheel = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarColor = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahBarColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarLength = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahBarLength;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahBarWidth = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahBarWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahCircleColor = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahCircleColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahDelayMillis = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahDelayMillis;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRadius = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahRadius;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimColor = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahRimColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahRimWidth = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahRimWidth;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahSpinSpeed = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahSpinSpeed;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahText = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahText;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextColor = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahTextColor;
			global::AndroidHUD.Resource.Styleable.ProgressWheel_ahTextSize = global::PurposeColor.Droid.Resource.Styleable.ProgressWheel_ahTextSize;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::PurposeColor.Droid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::PurposeColor.Droid.Resource.String.Hello;
			global::Xamarin.Forms.Platform.Resource.String.ApplicationName = global::PurposeColor.Droid.Resource.String.ApplicationName;
			global::Xamarin.Forms.Platform.Resource.String.Hello = global::PurposeColor.Droid.Resource.String.Hello;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int ahBarColor = 2130771974;
			
			// aapt resource value: 0x7f01000e
			public const int ahBarLength = 2130771982;
			
			// aapt resource value: 0x7f01000d
			public const int ahBarWidth = 2130771981;
			
			// aapt resource value: 0x7f01000b
			public const int ahCircleColor = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int ahDelayMillis = 2130771978;
			
			// aapt resource value: 0x7f01000c
			public const int ahRadius = 2130771980;
			
			// aapt resource value: 0x7f010007
			public const int ahRimColor = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int ahRimWidth = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int ahSpinSpeed = 2130771977;
			
			// aapt resource value: 0x7f010003
			public const int ahText = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int ahTextColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int ahTextSize = 2130771973;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050009
			public const int common_action_bar_splitter = 2131034121;
			
			// aapt resource value: 0x7f050000
			public const int common_signin_btn_dark_text_default = 2131034112;
			
			// aapt resource value: 0x7f050002
			public const int common_signin_btn_dark_text_disabled = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_signin_btn_dark_text_focused = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int common_signin_btn_dark_text_pressed = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int common_signin_btn_default_background = 2131034120;
			
			// aapt resource value: 0x7f050004
			public const int common_signin_btn_light_text_default = 2131034116;
			
			// aapt resource value: 0x7f050006
			public const int common_signin_btn_light_text_disabled = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_signin_btn_light_text_focused = 2131034119;
			
			// aapt resource value: 0x7f050005
			public const int common_signin_btn_light_text_pressed = 2131034117;
			
			// aapt resource value: 0x7f05000a
			public const int common_signin_btn_text_dark = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int common_signin_btn_text_light = 2131034123;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int circle = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_full_open_on_phone = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_ic_googleplayservices = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_signin_btn_icon_dark = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_signin_btn_icon_disabled_dark = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_signin_btn_icon_disabled_focus_dark = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_signin_btn_icon_disabled_focus_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_signin_btn_icon_disabled_light = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_signin_btn_icon_focus_dark = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_signin_btn_icon_focus_light = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_signin_btn_icon_light = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_signin_btn_icon_normal_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_signin_btn_icon_normal_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_signin_btn_icon_pressed_dark = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_signin_btn_icon_pressed_light = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_signin_btn_text_dark = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_signin_btn_text_disabled_dark = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_signin_btn_text_disabled_focus_dark = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_signin_btn_text_disabled_focus_light = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_signin_btn_text_disabled_light = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_signin_btn_text_focus_dark = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int common_signin_btn_text_focus_light = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int common_signin_btn_text_light = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int common_signin_btn_text_normal_dark = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int common_signin_btn_text_normal_light = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int common_signin_btn_text_pressed_dark = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int common_signin_btn_text_pressed_light = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int ic_errorstatus = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int ic_plusone_medium_off_client = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_plusone_small_off_client = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_plusone_standard_off_client = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_plusone_tall_off_client = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_successstatus = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int icon = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int roundedbg = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int roundedbgdark = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int splash = 2130837540;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080000
			public const int adjust_height = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int adjust_width = 2131230721;
			
			// aapt resource value: 0x7f080005
			public const int loadingImage = 2131230725;
			
			// aapt resource value: 0x7f080003
			public const int loadingProgressBar = 2131230723;
			
			// aapt resource value: 0x7f080006
			public const int loadingProgressWheel = 2131230726;
			
			// aapt resource value: 0x7f080002
			public const int none = 2131230722;
			
			// aapt resource value: 0x7f080004
			public const int textViewStatus = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int google_play_services_version = 2131099648;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int loading = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int loadingimage = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int loadingprogress = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040023
			public const int ApplicationName = 2130968611;
			
			// aapt resource value: 0x7f040022
			public const int Hello = 2130968610;
			
			// aapt resource value: 0x7f040001
			public const int auth_google_play_services_client_facebook_display_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int auth_google_play_services_client_google_display_name = 2130968576;
			
			// aapt resource value: 0x7f040004
			public const int common_android_wear_notification_needs_update_text = 2130968580;
			
			// aapt resource value: 0x7f040011
			public const int common_android_wear_update_text = 2130968593;
			
			// aapt resource value: 0x7f04000f
			public const int common_android_wear_update_title = 2130968591;
			
			// aapt resource value: 0x7f04001f
			public const int common_google_play_services_api_unavailable_text = 2130968607;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_enable_button = 2130968589;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_text = 2130968588;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_title = 2130968587;
			
			// aapt resource value: 0x7f040006
			public const int common_google_play_services_error_notification_requested_by_msg = 2130968582;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_install_button = 2130968586;
			
			// aapt resource value: 0x7f040008
			public const int common_google_play_services_install_text_phone = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int common_google_play_services_install_text_tablet = 2130968585;
			
			// aapt resource value: 0x7f040007
			public const int common_google_play_services_install_title = 2130968583;
			
			// aapt resource value: 0x7f040017
			public const int common_google_play_services_invalid_account_text = 2130968599;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_invalid_account_title = 2130968598;
			
			// aapt resource value: 0x7f040005
			public const int common_google_play_services_needs_enabling_title = 2130968581;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_network_error_text = 2130968597;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_network_error_title = 2130968596;
			
			// aapt resource value: 0x7f040003
			public const int common_google_play_services_notification_needs_update_title = 2130968579;
			
			// aapt resource value: 0x7f040002
			public const int common_google_play_services_notification_ticker = 2130968578;
			
			// aapt resource value: 0x7f040021
			public const int common_google_play_services_sign_in_failed_text = 2130968609;
			
			// aapt resource value: 0x7f040020
			public const int common_google_play_services_sign_in_failed_title = 2130968608;
			
			// aapt resource value: 0x7f040018
			public const int common_google_play_services_unknown_issue = 2130968600;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unsupported_text = 2130968602;
			
			// aapt resource value: 0x7f040019
			public const int common_google_play_services_unsupported_title = 2130968601;
			
			// aapt resource value: 0x7f04001b
			public const int common_google_play_services_update_button = 2130968603;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_update_text = 2130968592;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_update_title = 2130968590;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_updating_text = 2130968595;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_updating_title = 2130968594;
			
			// aapt resource value: 0x7f04001e
			public const int common_open_on_phone = 2130968606;
			
			// aapt resource value: 0x7f04001c
			public const int common_signin_button_text = 2130968604;
			
			// aapt resource value: 0x7f04001d
			public const int common_signin_button_text_long = 2130968605;
			
			// aapt resource value: 0x7f040024
			public const int library_name = 2130968612;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Theme_Splash = 2131165184;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] LoadingImageView = new int[]
			{
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] ProgressWheel = new int[]
			{
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 3
			public const int ProgressWheel_ahBarColor = 3;
			
			// aapt resource value: 11
			public const int ProgressWheel_ahBarLength = 11;
			
			// aapt resource value: 10
			public const int ProgressWheel_ahBarWidth = 10;
			
			// aapt resource value: 8
			public const int ProgressWheel_ahCircleColor = 8;
			
			// aapt resource value: 7
			public const int ProgressWheel_ahDelayMillis = 7;
			
			// aapt resource value: 9
			public const int ProgressWheel_ahRadius = 9;
			
			// aapt resource value: 4
			public const int ProgressWheel_ahRimColor = 4;
			
			// aapt resource value: 5
			public const int ProgressWheel_ahRimWidth = 5;
			
			// aapt resource value: 6
			public const int ProgressWheel_ahSpinSpeed = 6;
			
			// aapt resource value: 0
			public const int ProgressWheel_ahText = 0;
			
			// aapt resource value: 1
			public const int ProgressWheel_ahTextColor = 1;
			
			// aapt resource value: 2
			public const int ProgressWheel_ahTextSize = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
